import React, { useState, useEffect } from 'react';
import './CookieManagement.css';

const { ipcRenderer } = window.require('electron');

function CookieManagement() {
  const [cookies, setCookies] = useState([]);
  const [selectedCookies, setSelectedCookies] = useState([]);
  const [status, setStatus] = useState({ message: '', type: '' });
  const [editingCookie, setEditingCookie] = useState(null);
  const [loginStatus, setLoginStatus] = useState({ loggedIn: false, domains: [], cookieCount: 0 });

  useEffect(() => {
    loadCookies();
    loadLoginStatus();
  }, []);

  const showStatus = (message, type) => {
    setStatus({ message, type });
    setTimeout(() => setStatus({ message: '', type: '' }), 5000);
  };

  const loadLoginStatus = async () => {
    const result = await ipcRenderer.invoke('check-login-status');
    if (result.success) {
      setLoginStatus(result);
    }
  };

  const loadCookies = async () => {
    const result = await ipcRenderer.invoke('load-cookies');
    if (result.success && result.content) {
      // Parse cookies from Netscape format
      const lines = result.content.split('\n');
      const parsedCookies = lines
        .filter(line => line.trim() && !line.startsWith('#'))
        .map((line, index) => {
          const parts = line.split('\t');
          if (parts.length >= 7) {
            return {
              id: index,
              domain: parts[0],
              flag: parts[1],
              path: parts[2],
              secure: parts[3],
              expiration: parts[4],
              name: parts[5],
              value: parts[6]
            };
          }
          return null;
        })
        .filter(cookie => cookie !== null);
      
      setCookies(parsedCookies);
    } else {
      setCookies([]);
    }
  };

  const saveCookies = async (updatedCookies) => {
    // Convert back to Netscape format
    let cookieContent = '# Netscape HTTP Cookie File\n';
    cookieContent += '# This file was generated by Video Downloader. Edit at your own risk.\n\n';
    
    updatedCookies.forEach(cookie => {
      cookieContent += `${cookie.domain}\t${cookie.flag}\t${cookie.path}\t${cookie.secure}\t${cookie.expiration}\t${cookie.name}\t${cookie.value}\n`;
    });

    const result = await ipcRenderer.invoke('save-cookies', cookieContent);
    if (result.success) {
      await loadCookies();
      await loadLoginStatus();
      return true;
    }
    return false;
  };

  const handleDeleteAll = async () => {
    if (!window.confirm('Are you sure you want to delete ALL cookies? This cannot be undone.')) {
      return;
    }

    const result = await ipcRenderer.invoke('clear-cookies');
    if (result.success) {
      setCookies([]);
      setSelectedCookies([]);
      await loadLoginStatus();
      showStatus('All cookies deleted successfully', 'success');
    } else {
      showStatus('Failed to delete cookies', 'error');
    }
  };

  const handleDeleteSelected = async () => {
    if (selectedCookies.length === 0) {
      showStatus('Please select cookies to delete', 'error');
      return;
    }

    if (!window.confirm(`Delete ${selectedCookies.length} selected cookie(s)?`)) {
      return;
    }

    const updatedCookies = cookies.filter(cookie => !selectedCookies.includes(cookie.id));
    const success = await saveCookies(updatedCookies);
    
    if (success) {
      setSelectedCookies([]);
      showStatus(`${selectedCookies.length} cookie(s) deleted successfully`, 'success');
    } else {
      showStatus('Failed to delete cookies', 'error');
    }
  };

  const handleDeleteOne = async (id) => {
    if (!window.confirm('Delete this cookie?')) {
      return;
    }

    const updatedCookies = cookies.filter(cookie => cookie.id !== id);
    const success = await saveCookies(updatedCookies);
    
    if (success) {
      showStatus('Cookie deleted successfully', 'success');
    } else {
      showStatus('Failed to delete cookie', 'error');
    }
  };

  const handleEditCookie = (cookie) => {
    setEditingCookie({ ...cookie });
  };

  const handleSaveEdit = async () => {
    if (!editingCookie) return;

    const updatedCookies = cookies.map(cookie => 
      cookie.id === editingCookie.id ? editingCookie : cookie
    );

    const success = await saveCookies(updatedCookies);
    
    if (success) {
      setEditingCookie(null);
      showStatus('Cookie updated successfully', 'success');
    } else {
      showStatus('Failed to update cookie', 'error');
    }
  };

  const handleSelectCookie = (id) => {
    setSelectedCookies(prev => 
      prev.includes(id) ? prev.filter(cid => cid !== id) : [...prev, id]
    );
  };

  const handleSelectAll = () => {
    if (selectedCookies.length === cookies.length) {
      setSelectedCookies([]);
    } else {
      setSelectedCookies(cookies.map(c => c.id));
    }
  };

  const handleLogin = async () => {
    const result = await ipcRenderer.invoke('open-login-window', 'https://www.youtube.com');
    if (result.success) {
      showStatus('Login window opened. Please login and close the window when done.', 'info');
      setTimeout(() => {
        loadCookies();
        loadLoginStatus();
      }, 2000);
    }
  };

  return (
    <div className="cookie-management">
      <div className="page-header">
        <h1>Cookie Management</h1>
        <p>Manage your saved login cookies</p>
      </div>

      {status.message && (
        <div className={`status-message status-${status.type} fade-in`}>
          {status.message}
        </div>
      )}

      <div className="card">
        <h2>Login Status</h2>
        <div className="login-status-card">
          <div className="status-info">
            <div className={`status-badge ${loginStatus.loggedIn ? 'logged-in' : ''}`}>
              {loginStatus.loggedIn ? `Logged in (${loginStatus.cookieCount} cookies)` : 'Not logged in'}
            </div>
            {loginStatus.domains && loginStatus.domains.length > 0 && (
              <div className="domain-badges">
                {loginStatus.domains.map((domain, idx) => (
                  <span key={idx} className="domain-badge">{domain}</span>
                ))}
              </div>
            )}
          </div>
          <button className="btn btn-primary" onClick={handleLogin}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15 3H19C19.5304 3 20.0391 3.21071 20.4142 3.58579C20.7893 3.96086 21 4.46957 21 5V19C21 19.5304 20.7893 20.0391 20.4142 20.4142C20.0391 20.7893 19.5304 21 19 21H15" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M10 17L15 12L10 7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              <path d="M15 12H3" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            Login
          </button>
        </div>
      </div>

      <div className="card">
        <div className="card-header">
          <h2>Cookies ({cookies.length})</h2>
          <div className="action-buttons">
            {cookies.length > 0 && (
              <>
                <button className="btn btn-secondary" onClick={handleSelectAll}>
                  {selectedCookies.length === cookies.length ? 'Deselect All' : 'Select All'}
                </button>
                <button 
                  className="btn btn-danger" 
                  onClick={handleDeleteSelected}
                  disabled={selectedCookies.length === 0}
                >
                  Delete Selected ({selectedCookies.length})
                </button>
                <button className="btn btn-danger" onClick={handleDeleteAll}>
                  Delete All
                </button>
              </>
            )}
          </div>
        </div>

        {cookies.length === 0 ? (
          <div className="empty-state">
            <svg width="64" height="64" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
            <p>No cookies found</p>
            <p className="empty-subtitle">Click "Login" above to save your login session</p>
          </div>
        ) : (
          <div className="cookie-list">
            {cookies.map(cookie => (
              <div key={cookie.id} className={`cookie-item ${selectedCookies.includes(cookie.id) ? 'selected' : ''}`}>
                <input
                  type="checkbox"
                  checked={selectedCookies.includes(cookie.id)}
                  onChange={() => handleSelectCookie(cookie.id)}
                  className="cookie-checkbox"
                />
                <div className="cookie-info">
                  <div className="cookie-name">{cookie.name}</div>
                  <div className="cookie-domain">{cookie.domain}</div>
                  <div className="cookie-path">{cookie.path}</div>
                </div>
                <div className="cookie-actions">
                  <button 
                    className="btn-icon btn-icon-edit" 
                    onClick={() => handleEditCookie(cookie)}
                    title="Edit"
                  >
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M11 4H4C3.46957 4 2.96086 4.21071 2.58579 4.58579C2.21071 4.96086 2 5.46957 2 6V20C2 20.5304 2.21071 21.0391 2.58579 21.4142C2.96086 21.7893 3.46957 22 4 22H18C18.5304 22 19.0391 21.7893 19.4142 21.4142C19.7893 21.0391 20 20.5304 20 20V13" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M18.5 2.5C18.8978 2.10217 19.4374 1.87868 20 1.87868C20.5626 1.87868 21.1022 2.10217 21.5 2.5C21.8978 2.89782 22.1213 3.43739 22.1213 4C22.1213 4.56261 21.8978 5.10217 21.5 5.5L12 15L8 16L9 12L18.5 2.5Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </button>
                  <button 
                    className="btn-icon btn-icon-delete" 
                    onClick={() => handleDeleteOne(cookie.id)}
                    title="Delete"
                  >
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M3 6H5H21" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                      <path d="M8 6V4C8 3.46957 8.21071 2.96086 8.58579 2.58579C8.96086 2.21071 9.46957 2 10 2H14C14.5304 2 15.0391 2.21071 15.4142 2.58579C15.7893 2.96086 16 3.46957 16 4V6M19 6V20C19 20.5304 18.7893 21.0391 18.4142 21.4142C18.0391 21.7893 17.5304 22 17 22H7C6.46957 22 5.96086 21.7893 5.58579 21.4142C5.21071 21.0391 5 20.5304 5 20V6H19Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {editingCookie && (
        <div className="modal-overlay" onClick={() => setEditingCookie(null)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h2>Edit Cookie</h2>
            <div className="input-group">
              <label>Name</label>
              <input
                type="text"
                value={editingCookie.name}
                onChange={(e) => setEditingCookie({...editingCookie, name: e.target.value})}
              />
            </div>
            <div className="input-group">
              <label>Value</label>
              <input
                type="text"
                value={editingCookie.value}
                onChange={(e) => setEditingCookie({...editingCookie, value: e.target.value})}
              />
            </div>
            <div className="input-group">
              <label>Domain</label>
              <input
                type="text"
                value={editingCookie.domain}
                onChange={(e) => setEditingCookie({...editingCookie, domain: e.target.value})}
              />
            </div>
            <div className="input-group">
              <label>Path</label>
              <input
                type="text"
                value={editingCookie.path}
                onChange={(e) => setEditingCookie({...editingCookie, path: e.target.value})}
              />
            </div>
            <div className="modal-actions">
              <button className="btn btn-success" onClick={handleSaveEdit}>
                Save Changes
              </button>
              <button className="btn btn-secondary" onClick={() => setEditingCookie(null)}>
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default CookieManagement;
